### ISSUE TITLE
linuxdeploy --init-appdir  - no such option

### ISSUE THREAD

**Issue by asashnov** [AppImage/docs.appimage.org#12]
https://docs.appimage.org/packaging-guide/native-binaries.html

Example:
```
# run linuxdeploy and generate an AppImage
> ./linuxdeploy-x86_64.AppImage --appdir AppDir --init-appdir
```
But the current version of linuxdeploy doesn't have --init-appdir option!

**Comment by TheAssassin** [comment]
@asashnov will update the docs immediately, thanks for the hint, sorry for the inconvenience. The parameter was removed last week.
