### ISSUE TITLE
Document X-AppImage-... keys

### ISSUE THREAD

**Issue by probonopd** [AppImage/docs.appimage.org#14]
Continuation of https://github.com/AppImage/AppImageKit/issues/59

**Comment by TheAssassin** [comment]
If you can provide a list someone can put them in. Or you just do it yourself. It's not hard.

**Comment by probonopd** [comment]
Quoting you (from the linked ticket):

>  Many features are undocumented right now. _Please open an issue in the docs repository._

;-)

**Comment by TheAssassin** [comment]
So, more of an issue for there?
