### ISSUE TITLE
Generate PDF/ePub files and publish them along with HTML version

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/docs.appimage.org#18]
Some users request "offline formats" which allow for downloading the docs to read them while not connected to the Internet.

Sphinx allows for generating PDF/ePub files, and it shouldn't be very much of a problem to generate those in our build system and publish them along with our HTML pages.

We need to put a comment there, though, which warns users that the information might get outdated. Since we don't version our docs, you can't really tell when docs have changed, so the files should at least have the date of generation or so (and maybe the short commit hash) in their filename.

**Comment by Bronzu** [comment]
Thank you for considering my suggestion! Kind regards, and thank you once again. 
-Kacper

**Comment by TheAssassin** [comment]
Experimental ePub downloads added. See https://docs.appimage.org/ (scroll down).

PDF won't happen very soon, as it requires some sort of LaTeX distribution (@probonopd before you ask, yes, pandoc _also_ requires LaTeX for that).

**Comment by probonopd** [comment]
WIll be loading the EPUBs on my dedicated reading device right now. 👍 Thank you @TheAssassin
