### ISSUE TITLE
Create a simple "how to run an appimage" page

### ISSUE THREAD

**Issue by aoloe** [AppImage/docs.appimage.org#20]
in the documentation there is a longer page that starts very well, but then goes on with "scary" details:

https://docs.appimage.org/user-guide/run-appimages.html

on the main page there is a link to a youtube video with instruction only for the the terminal.

it would be nice to have a single page with first section of the docs on running Appimages plus the videos that can be linked from projects that are using Appimages. (without any reference on how to unpack an appimage file...  : - )

**Comment by TheAssassin** [comment]
We could break up the page into two or three consecutive but separate pages. Would that be better?

**Comment by aoloe** [comment]
maybe, yes...

the inkscape folks have done this:

https://inkscape.org/de/release/inkscape-master/gnulinux/appimage/dl/

i'd like to have something similar to that, also showing how to do it with a GUI that i can link to.

i guess that 

https://docs.appimage.org/user-guide/run-appimages.html

from "# Running AppImages" to "That’s it! The AppImage should now be executed." should be good.

i did not have a look at the videos on the homepage, but they might also fit.

personally, i think it would be better to create a separate page for this, with links to the docs for more information, but separating the page in sections inside of the documentation is probably also a good choice.

do whatever is simpler for you : - )

**Comment by TheAssassin** [comment]
I've created a quickstart page in our Intro, it's the first page now, and there's a link from the homepage. I just moved the contents you suggested.

Thanks again for the pointer, really appreciated. The new structure is much better and much more helpful.

**Comment by aoloe** [comment]
thanks!

the content of "How to run an AppImage?" is now good.

three more remarks from my side:

- make the content of the "how to run an appimage" left aligned.
- at some time redo the intro video with an english desktop environment (and no read mode popup : - ).
- change the next title "how it works" to "how to create an appimage" or similar and move it down towards the end of the page. imo there is a need for a better separation between "consumer" and "producer" of an appimage. (too many people tend to be so insecure when working with computers...)

**Comment by TheAssassin** [comment]
> make the content of the "how to run an appimage" left aligned.

Not entirely sure what you mean with "make it left aligned", it *is* left aligned, if you ask me.

![screenshot_2019-09-01_23-45-21](https://user-images.githubusercontent.com/4503202/64082668-c3d2fa80-cd12-11e9-8f8d-112a9d50d716.png)

> at some time redo the intro video with an english desktop environment (and no read mode popup : - ).

You're right about the intro video. @probonopd can you help us there? You made the last one, so perhaps you can make a more up to date, English one?

> change the next title "how it works" to "how to create an appimage" or similar and move it down towards the end of the page. imo there is a need for a better separation between "consumer" and "producer" of an appimage. (too many people tend to be so insecure when working with computers...)

So, you want a chapter about making AppImages in the Quickstart? Can you please describe what needs to be done? Perhaps make a new issue, this one's more about the "consumer" side.

**Comment by aoloe** [comment]
i was writing about:

![appiamge-left](https://user-images.githubusercontent.com/1857016/64124947-b405f580-cda8-11e9-9bee-19db08326fb3.png)

**Comment by aoloe** [comment]
that looks like: "that was easy, wasn't it?"

... now we will bother you with all the complex things you never wanted to know about : - )

**Comment by aoloe** [comment]
<https://docs.appimage.org/introduction/quickstart.html#how-to-run-an-appimage> is fine!

**Comment by probonopd** [comment]
I'd edit it quickly on the homepage if I didn't have to fear that I break all the Weblate stuff...

**Comment by TheAssassin** [comment]
Perhaps we should just link to the docs instead of keeping information redundantly. I'd like to increase the docs' visibility.

**Comment by probonopd** [comment]
No one reads docs, remember ;-) Everything needed to run AppImages needs to be on the homepage, _ideally_ visible without scrolling down.

**Comment by TheAssassin** [comment]
Redundant information creates work for me. A link doesn't. Also keeps things consistent. And we all like consistency.

**Comment by aoloe** [comment]
personally, i feel that the appimage website has the right type and amount of the content.
of course it can be done differently, but as it is it feels right.

of course, it's work to keep it up to date, but i think it fulfills a different task than the documentation.

**Comment by probonopd** [comment]
The main issue right now is that due to how we translate the webpage, everyone is afraid to touch it (at least I am) in fear of breaking something. Maybe we should turn it into a Jekyll page, like https://appimage.github.io/

**Comment by probonopd** [comment]
What happens if someone needs to change the whole page? Then the tagging that is used for Weblate breaks entirely. Maybe it would be easier to have just 5 separate `.md` pages for the 5 main languages or so? it would take the "fear of breaking something" out of the equation, at least for me.

**Comment by TheAssassin** [comment]
We *have* such a system. Just change the English text on Weblate, or add new tags and remove old ones. Weblate can then be fed with new texts. And Weblate shows which parts need to be translated yet. The current system furthermore ensures there's an English fallback if a native translation is not available.
You always complain, but you never took the time to look into any of the docs related to the system, have you?

**Comment by probonopd** [comment]
No. I rarely ever read docs due to an ever-present lack of time. Hence I prefer simple tools that "just work" without one having to read any docs.

**Comment by TheAssassin** [comment]
But you *have* read the docs on Jekyll? Or is that just how you guess that system works?

**Comment by probonopd** [comment]
I copied an existing project and went from there, with Google-Trial-and-Error.
