### ISSUE TITLE
This document is currently work in progress

### ISSUE THREAD

**Issue by probonopd** [AppImage/docs.appimage.org#23]
> This document is currently work in progress. Contributions welcome!

When will this be removed, and the docs will no more be "work in progress"?

**Comment by TheAssassin** [comment]
It will always be. I'd like to keep an invitation for contributions. Any suggestions for different texts welcome.

**Comment by probonopd** [comment]
How about, instead of

> This document is currently work in progress. 

we could write

> We are always looking for ways to improve the documentation.

**Comment by TheAssassin** [comment]
That's like "it sucks and we have good intentions but... not really".

**Comment by probonopd** [comment]
Maybe better remove that sentence altogether then :-)

**Comment by TheAssassin** [comment]
You are the only one who's got a problem with that sentence...

**Comment by probonopd** [comment]
Implying that documentation is incomplete would be a big red flag for me when I see a project for the first time. Like the "under construction" animated GIFs on all websites in the early 2000s.

**Comment by TheAssassin** [comment]
The documentation is far from being finished. You may help complete it, then we can remove that notice. But people should know that if parts are missing, that doesn't mean certain things are not possible, for instance, but they're just not documented. Big difference.

**Comment by probonopd** [comment]
True. Do you know which areas are missing/lacking?

**Comment by TheAssassin** [comment]
Well, it's hard to judge what's missing exactly. I often open issues when there's users asking questions that aren't covered adequately yet. But I have a broad knowledge about all aspects of AppImage, so I might things more obvious than regular users.

As said, the word `currently` is probably no longer adequate, but I'd like to invite people to contribute. I wrote the current words, and I'm still fine with them. If you want something else, you should come up with something better. I think we both agree removing it entirely is also far from optimal.

**Comment by probonopd** [comment]
How about

> This document is continuously improved, your contributions are welcome.

**Comment by TheAssassin** [comment]
That implies that _we_ are working on it, but we want to invite people like "This document could use your help".

**Comment by probonopd** [comment]
"your contributions are welcome" is meant to say exactly that.

**Comment by TheAssassin** [comment]
How about something along

> You're welcome to contribute and improve the AppImage documentation. Please feel free to send a PR whenever you notice some topics aren't covered adequately, or there's bugs.

**Comment by probonopd** [comment]
More verbose, but OK with me. (I like minimalism.)

**Comment by TheAssassin** [comment]
I still like the original, short wording. I don't see why this should be changed (other than removing the word "currently")...

**Comment by probonopd** [comment]
Because it screams "This documentation is crap, don't rely on it, it is WIP". When I read something like this in some project, I usually wait until it's no longer WIP and then I consider using it.

**Comment by TheAssassin** [comment]
Last attempt:

> This documentation contains a lot of valuable information, but there’s always some information to add. Contributions welcome!

I think that expresses quite well what I want to say with the statement.

**Comment by probonopd** [comment]
OK :+1:

**Comment by TheAssassin** [comment]
Closed via 7f43397.
