### ISSUE TITLE
Most OBS links are broken

### ISSUE THREAD

**Issue by probonopd** [AppImage/docs.appimage.org#24]
https://docs.appimage.org/packaging-guide/obs.html#working-examples

Most of these are broken. Why?

- https://build.opensuse.org/package/binaries/home:probono/QtQuickApp?repository=AppImage
- https://build.opensuse.org/package/binaries/home:probono/DSRemote?repository=AppImage
- https://build.opensuse.org/package/binaries/home:probono/Qactus?repository=AppImage
- https://build.opensuse.org/package/binaries/home:probono/leafpad?repository=AppImage
- https://github.com/olav-st/screencloud/blob/master/deploy/linux/appimage.yml
- https://build.opensuse.org/package/view_file/home:pbek:QOwnNotes/desktop/appimage.yml?expand=1
- https://build.opensuse.org/package/view_file/home:olav-st:branches:OBS:AppImage:Templates/ScreenCloud/appimage.yml?expand=1
- https://build.opensuse.org/package/view_file/home:pbartfai/LDView/_service:extract_file:appimage.yml?expand=1
- https://build.opensuse.org/package/view_file/home:lachs0r:mandelbulber2/mandelbulber2/appimage.yml?expand=1
- https://build.opensuse.org/package/view_file/home:lachs0r:taisei/taisei/appimage.yml?expand=1

Despite all the greatness of OBS, this is exactly the impression I get: you set stuff up, then wait a year, and then it's not guaranteed to be working anymore... or is it my fault?

**Comment by probonopd** [comment]
Before we change the docs I'd like to understand why the https://build.opensuse.org/package/binaries/home:probono are not working anymore. I haven't touched them in years.

**Comment by TheAssassin** [comment]
That's why absolute links suck, and why URL redirection services still are an important layer of abstraction for services.

**Comment by TheAssassin** [comment]
Fixed a few, couldn't find some `binaries` link stuff any more, so I've made them work at least, by linking to the project pages. Better than leaving them broken.

A few projects have been removed altogether anyway.
