### ISSUE TITLE
Documentation does not mention that envvar OWD is set for type 2 appimage binaries.

### ISSUE THREAD

**Issue by crass** [AppImage/docs.appimage.org#26]
While looking through the [code](../blob/master/src/runtime.c#L907) and the [docs](https://docs.appimage.org/packaging-guide/environment-variables.html). I noticed that the docs do not mention that `OWD` is also set for type 2 appimage binaries.

**Comment by TheAssassin** [comment]
I guess the use cases for that env var are pretty rare. Also I'm not sure how long this var has existed.

Mind to send a PR?

**Comment by TheAssassin** [comment]
Also for type 1 we don't have a SquashFS but an ISO9660 image.

**Comment by crass** [comment]
I mention in the interest of completeness.  Maybe someone cares to do something about it.  I'm not really motivated to make and test a PR.  I wonder if anyone is even using it in type 2.  I don't understand what the image type (ISO vs squash) has anything to do with it though...

**Comment by TheAssassin** [comment]
I'll fix it, don't worry.
