### ISSUE TITLE
Update oldest still-supported Ubuntu version

### ISSUE THREAD

**Issue by bugwelle** [AppImage/docs.appimage.org#33]
From: https://github.com/AppImage/docs.appimage.org/blob/master/source/packaging-guide/distribution.rst

> Must run on the oldest still-supported Ubuntu LTS release (currently Ubuntu 14.04) 

That should be 16.04 :)

https://github.com/AppImage/appimage.github.io/blob/master/README.md apparently has already been updated. :smiley: 

I don't know whether there are further inconsistencies. Thanks.

**Comment by TheAssassin** [comment]
I will replace that with a link to the Ubuntu release page or Wikipedia or something. Thanks for the hint.

**Comment by TheAssassin** [comment]
Fixed. Thanks again.

**Comment by TheAssassin** [comment]
P.S.: Feel free to send PRs directly if you discover out of date information.

**Comment by bugwelle** [comment]
b4a4a531c68bdebfdde43bb0a163399614b1a6ca for reference.

> P.S.: Feel free to send PRs directly if you discover out of date information.

Yeah, but I didn't know how you would like to handle this. If I find any typos, I'll create a PR :) 
Thank you for updating the documentation.
