### ISSUE TITLE
dead link: https://docs.appimage.org/packaging-guide/yml-example-file

### ISSUE THREAD

**Issue by mehlon** [AppImage/docs.appimage.org#38]
In [pkg2appimage](https://docs.appimage.org/packaging-guide/pkg2appimage.html) there's a dead link to https://docs.appimage.org/packaging-guide/yml-example-file

**Comment by TheAssassin** [comment]
That page is deprecated and shouldn't be there at all. New location is https://docs.appimage.org/packaging-guide/converting-binary-packages/pkg2appimage.html.

That link is dead indeed. @probonopd any idea where it linked to? Otherwise we can just remove that link, there's YML examples in the text.

**Comment by probonopd** [comment]
Don't know where it had linked to, but I think https://github.com/AppImage/pkg2appimage/tree/master/recipes should be fine.
