### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by wiltaylor** [AppImage/docs.appimage.org#39]
Your SSL certificate expired today 23/12/2019. Looks like your lets-encrypt script to renew it isn't triggering in time or stopped working.

I am also located in Australia if that helps since we are day ahead date wise.

**Comment by TheAssassin** [comment]
Certbot has screwed up its installation somehow. Thanks for the hint, I also noticed the problem just now. I reinstalled the software and it's renewed the certificate.
