### ISSUE TITLE
AppImageBuilder documentation

### ISSUE THREAD

**Issue by azubieta** [AppImage/docs.appimage.org#41]
After some successfully built AppImages:
 - (regular Qt+QML App) https://github.com/llamaret/MystiQ/releases/tag/continuous
 - (Retro game wrote in Java) https://www.opencode.net/azubieta/planetmule-appimage
 - the project source includes other working recipes such as VLC, gnome-calculator, KCalc, wget and echo.

I guess it's time to document it. So I was wondering whether you prefer to have this documentation as part of doc.appimage.org or just add a reference to it?

**Comment by TheAssassin** [comment]
The documentation is IMO better done externally. I intend to extract e.g., the linuxdeploy user guide, as well.

**Comment by azubieta** [comment]
Seems reasonable, let's keep on doc.appimage.org only the information related to the core aspects of AppImage and put the tools apart.

**Comment by azubieta** [comment]
Done at f1bd73886f2488ad3edde83f4137f3bc2e3b6653
