### ISSUE TITLE
The page AppImageKit-checkrt is undiscoverable (has no links to it)

### ISSUE THREAD

**Issue by dimztimz** [AppImage/docs.appimage.org#44]
The following page https://github.com/AppImage/docs.appimage.org/blob/master/source/packaging-guide/advanced/troubleshooting.rst has no links from the rest of the documentation to it.

**Comment by TheAssassin** [comment]
How is the lack of links to the site a problem? You mean, it has not been added to a toctree (table of contents tree)?
