### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/docs.appimage.org#46]
**At all contributors:**

This project has no clear licensing for its contents. I would like to make these docs available under the terms of the CC-By 4.0 Intl license (a rather liberal license).

I need every author with significant contributions to agree on this. Please answer to this issue whether it is okay for you to license your contributions under this license, or if you want to have them removed again.

- [x] @probonopd contributed some initial Markdown documents which were later converted to reST, as well as a few pages.
- [ ] @Taz8du29 converted most of the Markdown pages to the superior reST, with a few fixes and other minor contributions.
- [ ] @aferrero2707 provided some fixes and other smaller contributions
- [x] @Inventitech contributed one paragraph on how to update applications in AppImageHub

The remaining contributors mainly fixed typos and syntactical errors. I assume it is no problem copyright wise to license these, as they are, in comparison to the remaining works, insignificant changes. However, I highlight you so you can have a look yourself, since I think that is good style. @claell @asashnov @zhmars @fboender @daquexian @dandelionred @alexmyczko @Trilarion 

Please provide feedback until May 31, this issue should be sorted out very soon.

**Comment by probonopd** [comment]
My content that came from from https://github.com/AppImage/AppImageKIt/wiki is covered by https://github.com/AppImage/AppImageKit/blob/master/LICENSE but I am happy to dual-license it under _CC-By 4.0 Intl_ as well if this is beneficial.

**Comment by TheAssassin** [comment]
The MIT license, like any code license, is not really good for documentation or other non-code media. Therefore, re-/dual-licensing it is a good idea, yes.

The more liberal Creative Commons licenses are ideal for docs, [unlike the GNU FDL](https://www.debian.org/vote/2006/vote_001) they're easy to use for every party. The one I chose is like, "the MIT equivalent for docs", if you like. Software licenses do handle the difference between source and binary representation etc., which is not applicable to docs, really. There, we care more or less about the content only, no matter how it's rendered.

**Comment by Inventitech** [comment]
CC-By 4.0 Intl is fine by me.

**Comment by claell** [comment]
Thanks for the ping. Although probably not relevant, I am ok with the planned license. I was even thinking about using CC0, but attribution might be a good thing to have to prevent third parties using content out of context.

**Comment by TheAssassin** [comment]
@claell I think attribution is the least thing people can do.

Would you guys be okay to be referred to as "The AppImage team & docs contributors"? Then I'll change the footer.

**Comment by probonopd** [comment]
Minor nitpick, please use "and" not "&". The "&" symbol is mainly used for corporation names, it is not a general replacement for the word "and". (This is a stylistic thing.)

**Comment by claell** [comment]
@TheAssassin I guess that is up to personal preference. I like the idea to make things available as open as possible. However, I can understand that one would like to get at least credit when a larger amount of work is used on other websites. Speaking from a user perspective, I also had several instances when I would have liked to see a source of a tutorial instead of finding out later that parts of it were copied from an official documentation.

**Comment by Trilarion** [comment]
Full approval from my side, even though it was just a few corrected typos. Many regards.

**Comment by TheAssassin** [comment]
Time's over, I'm going to add this license. Thanks again to all contributors, your help is really appreciated.
I would ask @aferrero2707 and @Taz8du29 to get in touch if they disagree with the license.

**Comment by Taz8du29** [comment]
@TheAssassin It's all fine for me :)
