### ISSUE TITLE
External AppStream Generator is not working

### ISSUE THREAD

**Issue by openaudible** [AppImage/docs.appimage.org#61]
On this page:

https://docs.appimage.org/packaging-guide/optional/appstream.html

the link to:
http://output.jsbin.com/qoqukof

returns internal server error

**Comment by TheAssassin** [comment]
That's the issue when you rely on third party services. I'm pretty sure there's no backup of that script.

@probonopd might be able to provide more information.

**Comment by probonopd** [comment]
The code is mirrored at
https://gist.github.com/probonopd/45636fc168d3dbf71db2463bfa07319c

Looks like an issue of jsbin.com to me; maybe it is a temporary outage?

**Comment by TheAssassin** [comment]
You should probably just include it in the docs in some way. No reason for some third-party thing that can even go down.

**Comment by probonopd** [comment]
http://output.jsbin.com/qoqukof is still broken. Been almost a year now. Probably need to host the HTML page somewher else?

**Comment by probonopd** [comment]
> include it in the docs in some way

What would be a good way to do this?

**Comment by TheAssassin** [comment]
https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through

I can integrate it somewhere if you provide a complete (that is, including CSS/JS) HTML file.

**Comment by probonopd** [comment]
https://gist.githubusercontent.com/probonopd/45636fc168d3dbf71db2463bfa07319c/raw/40057bda0b3b40de7d9c70aa039a100311aa8e14/index.html - it has everything in one file.

**Comment by TheAssassin** [comment]
https://docs.appimage.org/packaging-guide/optional/appstream.html?highlight=appstream#using-the-appstream-generator

Fixed by [9df90fb](https://github.com/AppImage/docs.appimage.org/commit/9df90fb02ad8b13bca775adf508e349a83e1f54d).

**Comment by probonopd** [comment]
Splendid! Never thought it was possible to _integrate it into the documentation_ like this! :100:
