### ISSUE TITLE
Would you be open to adding an examples section ? 

### ISSUE THREAD

**Issue by weirdbricks** [AppImage/docs.appimage.org#64]
Hi,

I would like to issue a couple of PRs to add examples on how to create AppImages.

Would you be open to adding an examples section ? I can add a section for it in the PRs.

Thanks!

**Comment by pktiuk** [comment]
I think it would be quicker to just submit at least one PR with example code and wait.

In contributors list you can see some people which submitted single changes, and they are merged https://github.com/AppImage/docs.appimage.org/graphs/contributors 

I think you can close this issue and just submit PR ;)

**Comment by weirdbricks** [comment]
that's fair, thanks @pktiuk
