### ISSUE TITLE
Better describe registering and desktop integration process

### ISSUE THREAD

**Issue by pktiuk** [AppImage/docs.appimage.org#67]
I think it would be good to properly describe what is done during desktop integration process done using AppImageLauncher, and what are differences between it and using simple registering with libappimage (`appimage_register_in_system()`).

https://docs.appimage.org/reference/desktop-integration.html

I have already asked these questions to @probonopd on AppImage discourse, but I think it would be good to add these answers to docs to make integrating AppImages into stores easier.

**Comment by probonopd** [comment]
Please ask for that over at https://github.com/TheAssassin/AppImageLauncher/.
