### ISSUE TITLE
https://docs.appimage.org/ is offline.

### ISSUE THREAD

**Issue by will-ca** [AppImage/docs.appimage.org#89]
https://docs.appimage.org/

**Comment by TheAssassin** [comment]
Known issue. Working on it.

**Comment by TheAssassin** [comment]
Temporary mirror on https://appimage-docs.assassinate-you.net available. @probonopd will fix the DNS setup tonight.

**Comment by probonopd** [comment]
Up and running again. Thank you very much @TheAssassin.
